# Generated by Django 6.0.5 on 2026-05-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings_choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TOPPINGS', models.CharField(choices=[('pepperoni', 'Pepperoni'), ('mushrooms', 'Mushrooms'), ('onions', 'Onions')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='pizza.toppings_choice'),
        ),
    ]
